blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://discord.gg/W2GheK3F9m
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://discord.gg/W2GheK3F9m
    about: Please visit our Discord for general questions about Trexz.
